### ISSUE TITLE
better recommend `equalprg` than `formatprg` in `README.rst`

### ISSUE THREAD

**Issue by vlcinsky** [mindriot101/vim-yapf#9]
I feel, that `formatprg` is more for reflowing a text and `equalprg` to reindent a text.

The README shall thus recommend using `equalprg` and this can be done by adding:

    autocmd FileType python setlocal equalprg=yapf

into `.vimrc` file.

Reformatting the whole file can be (starting in normal mode) done by:

    gg=G

and reformatting currently selected lines simply:

    =

Of course, adding some leader command may help, but in this case it could be simply adding a leader command for reindenting text of any style (assuming some people use other indenters for other filetypes).

**Comment by simonrw** [comment]
You've taught me something about vim! I'll add this as an alternative, but `formatprg` is still a valid thing to use.
